INSERT INTO artist (nume) VALUES ('Iron Maiden');
INSERT INTO artist (nume) VALUES ('Metallica');
INSERT INTO artist (nume) VALUES ('Black Sabbath');
INSERT INTO artist (nume) VALUES ('AC/DC');
INSERT INTO artist (nume) VALUES ('Megadeth');

INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('The Number of the Beast', 1, 1982);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Powerslave', 1, 1984);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Seventh Son of a Seventh Son', 1, 1988);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Somewhere in Time', 1, 1986);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('The X Factor', 1, 1995);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Kill `Em All', 2, 1983);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Ride the Lightning', 2, 1984);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Master of Puppets', 2, 1986);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('...And Justice for All', 2, 1988);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Metallica (The Black Album)', 2, 1991);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Highway to Hell', 4, 1979);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Back in Black', 4, 1980);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('For Those About to Rock We Salute You', 4, 1981);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Razor s Edge', 4, 1990);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Black Ice', 4, 2008);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Paranoid', 3, 1970);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Master of Reality', 3, 1971);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Vol. 4', 3, 1972);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Sabbath Bloody Sabbath', 3, 1973);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Heaven and Hell', 3, 1980);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Peace Sells... But Who s Buying', 5, 1986);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Rust in Peace', 5, 1990);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Countdown to Extinction', 5, 1992);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Youthanasia', 5, 1994);
INSERT INTO audioalbum (titlu_album, id_artist, an) VALUES ('Cryptic Writings', 5, 1997);

INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Invaders', 1, '03:20');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Children of the Damned', 1, '04:34');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'The Prisoner', 1, '06:03');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, '22 Acacia Avenue', 1, '06:34');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'The Number of the Beast', 1, '04:51');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Run to the Hills', 1, '03:53');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Gangland', 1, '03:48');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Hallowed Be Thy Name', 1, '07:10');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Total Eclipse', 1, '04:25');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Aces High', 2, '04:29');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, '2 Minutes to Midnight', 2, '06:00');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Losfer Words (Big Orra)', 2, '04:15');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Flash of the Blade', 2, '04:06');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'The Duellists', 2, '06:06');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Back in the Village', 2, '05:03');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Powerslave', 2, '07:11');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Rime of the Ancient Mariner', 2, '13:45');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Moonchild', 3, '05:40');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Infinite Dreams', 3, '06:09');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Can I Play with Madness', 3, '03:31');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'The Evil That Men Do', 3, '04:34');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Seventh Son of a Seventh Son', 3, '09:53');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'The Prophecy', 3, '05:05');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'The Clairvoyant', 3, '04:27');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (1, 'Only the Good Die Young', 3, '04:42');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Hit the Lights', 6, '04:17');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'The Four Horsemen', 6, '07:13');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Motorbreath', 6, '03:08');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Jump in the Fire', 6, '04:41');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Anesthesia - Pulling Teeth', 6, '04:15');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Whiplash', 6, '04:06');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Phantom Lord', 6, '05:02');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'No Remorse', 6, '06:26');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Seek & Destroy', 6, '06:55');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Metal Militia', 6, '05:09');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Fight Fire with Fire', 7, '04:44');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Ride the Lightning', 7, '06:37');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'For Whom the Bell Tolls', 7, '05:10');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Fade to Black', 7, '06:57');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Trapped Under Ice', 7, '04:03');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Escape', 7, '04:24');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Creeping Death', 7, '06:36');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'The Call of Ktulu', 7, '08:52');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Battery', 8, '05:12');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Master of Puppets', 8, '08:35');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'The Thing That Should Not Be', 8, '06:36');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Welcome Home (Sanitarium)', 8, '06:27');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Disposable Heroes', 8, '08:14');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Leper Messiah', 8, '05:40');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Orion', 8, '08:12');
INSERT INTO audiotrack (id_artist, titlu_piesa, id_album, durata) VALUES (2, 'Damage, Inc', 8, '05:31');


INSERT INTO lyrics (id_audiotrack, lyrics) VALUES (1, 'Longboats have been sighted and the evidence of war has begun, many Nordic fighting men, their swords and shields all gleam in the sun, call to arms, defend yourselves, get ready to stand and fight for your lives');
INSERT INTO lyrics (id_audiotrack, lyrics) VALUES (2, 'He s walking like a small child, but watch his eyes burn you away, black holes in his golden stare, God knows he wants to go home, children of the damned, children of the damned, children of the damned, children of the damned');
INSERT INTO lyrics (id_audiotrack, lyrics) VALUES (3, 'Not a prisoner, I`m a free man, and my blood is my own now, don`t care where the past was, I know where I`m going, out');
INSERT INTO lyrics (id_audiotrack, lyrics) VALUES (4, 'If you`re feeling down, depressed and lonely, I know a place where we can go, 22 Acacia Avenue, meet a lady that I know, so if you`re looking for a good time, and you`re prepared to pay the price, fifteen quid is all she asks for, everybody`s got their vice');
INSERT INTO lyrics (id_audiotrack, lyrics) VALUES (5, 'Woe to you, oh Earth and Sea, for the Devil sends the beast with wrath, because he knows the time is short, let him who hath understanding reckon the number of the beast, for it is a human number, its number is six hundred and sixty six');

INSERT INTO authority(role) VALUES('ADMIN');
INSERT INTO authority(role) VALUES('USER');

INSERT INTO app_user (username, nume, prenume, password, authority_id, account_not_expired, account_not_locked, credentials_not_expired, enabled) VALUES ('a', 'TITA', 'Valentin', 'aaaaa', 1, 1, 1, 1, 1);
INSERT INTO app_user (username, nume, prenume, password, authority_id, account_not_expired, account_not_locked, credentials_not_expired, enabled) VALUES ('b', 'TITA', 'Valentin', 'bbbbb', 2, 1, 1, 1, 1);
INSERT INTO app_user (username, nume, prenume, password, authority_id, account_not_expired, account_not_locked, credentials_not_expired, enabled) VALUES ('elvantin@gmail.com', 'TITA', 'Valentin', 'ElvantinPa$$', 1, 1, 1, 1, 1);
INSERT INTO app_user (username, nume, prenume, password, authority_id, account_not_expired, account_not_locked, credentials_not_expired, enabled) VALUES ('ionut78@example.com', 'Ionescu', 'Ionut', 'parolaionut', 2, 1, 1, 1, 1);
INSERT INTO app_user (username, nume, prenume, password, authority_id, account_not_expired, account_not_locked, credentials_not_expired, enabled) VALUES ('marius23@example.com', 'Popa', 'Marius', 'parolamarius', 2, 1, 1, 1, 1);
INSERT INTO app_user (username, nume, prenume, password, authority_id, account_not_expired, account_not_locked, credentials_not_expired, enabled) VALUES ('elena84@example.com', 'Georgescu', 'Elena', 'parolaelena', 2, 1, 1, 1, 1);
INSERT INTO app_user (username, nume, prenume, password, authority_id, account_not_expired, account_not_locked, credentials_not_expired, enabled) VALUES ('alex21@example.com', 'Dumitru', 'Alexandru', 'parolaalex', 2, 1, 1, 1, 1);

INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 1, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 2, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 3, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 4, 2);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 5, 1);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 1, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 2, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 3, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 4, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 5, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 1, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 2, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 3, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 4, 1);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 5, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 1, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 2, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 3, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 4, 2);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 5, 1);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 1, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 2, 2);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 3, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 4, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 5, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 6, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 6, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 6, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 6, 1);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 6, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 7, 2);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 7, 1);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 7, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 7, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 7, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (1, 8, 4);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (2, 8, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (3, 8, 3);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (4, 8, 5);
INSERT INTO rating (id_persoana, id_audiotrack, rating) VALUES (5, 8, 4);